### ISSUE TITLE
HOW CAN I MAKE IT VERTICAL AND ALSO PUT THE OUTPUT ON THE FRONT 

### ISSUE THREAD

**Issue by akpobi** [CodyHouse/responsive-tabbed-navigation#3]

**Comment by claudia-romano** [comment]
Hi there! Unfortunately, we can't help with the customization of the resource. I can't count this as an "issue", so I'm gonna have to close the issue here on GitHub.

**Comment by samadah** [comment]
You can use CSS to float menu right. You need to create two divs that will each hold parts of the tabs, then float left, there may be more properties to add to your CSS such as responsive width etc...Good luck
