### ISSUE TITLE
Menu upright

### ISSUE THREAD

**Issue by groupunknown** [CodyHouse/responsive-tabbed-navigation#4]
Sorry for my ignorance, but how to put the menu upright?

I tried everything and could not ...

**Comment by samadah** [comment]
You can use CSS to float menu right. You need to create two divs that will each hold parts of the tabs, then float left, there may be more properties to add to your CSS such as responsive width etc...Good luck

**Comment by outercapeweb** [comment]
vertical menu - i can't find it either. it says this, but gives no explanation: "We used CSS media queries to change the navigation positioning from horizontal to vertical, and vice versa."

**Comment by claudia-romano** [comment]
Hi there, we have just released a new version (2.0) of this experiment (based on the [CodyHouse framework](https://codyhouse.co/ds/docs/framework)).

To keep the navigation vertical, you can remove the scss code inside the md breakpoint (you'll find comments in the style.scss file to show you which parts to remove).

**Comment by outercapeweb** [comment]
bless you! thanks.
